apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: node-redis-autoscaling
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 1
          type: Utilization
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-redis